/*
 * @file /parastation-core/src/spu/backend.rs
 * @brief
 * Backend trait for playing samples generated by the SPU.
 * Implemented by the frontend so the core can stay platform agnostic.
 * -----
 */

// Imports
use crate::spu::PcmSample;

pub trait SpuBackend {
    /// Push one tick's worth of stereo output. Called once per SPU tick (44.1kHz)
    fn push_sample(&mut self, left: PcmSample, right: PcmSample);

    /// How many samples the backend's internal buffer can currently accept
    fn buffer_available(&self) -> usize;
}
